apiVersion: v1
kind: Secret
metadata:
  name: custom-tls
  namespace: garden-dev    # change it to your project namespace, e.g., garden-<my-project-name>
data:
  ca.crt: >-
    LS0tLS1.......
type: Opaque