---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-audit-policy
  namespace: garden-local
data:
  policy: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    omitStages:
      - "RequestReceived"
    rules:
      - level: RequestResponse
        resources:
        - group: ""
          resources: ["pods"]
      - level: Metadata
        resources:
        - group: ""
          resources: ["pods/log", "pods/status"]
