---
apiVersion: v1
kind: Secret
metadata:
  name: splunk-secret
  namespace: garden-local
stringData:
  hecToken: <hec token>
  caFile: |
    -----BEGIN CERTIFICATE-----
    <cert>
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    <cert>
    -----END CERTIFICATE-----
