//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2023 Copyright metal-stack.
*/

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&AuditConfig{}, func(obj interface{}) { SetObjectDefaults_AuditConfig(obj.(*AuditConfig)) })
	return nil
}

func SetObjectDefaults_AuditConfig(in *AuditConfig) {
	SetDefaults_AuditConfig(in)
	SetDefaults_AuditPersistence(&in.Persistence)
}
