//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2023 Copyright metal-stack.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	audit "github.com/metal-stack/gardener-extension-audit/pkg/apis/audit"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AuditBackendLog)(nil), (*audit.AuditBackendLog)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuditBackendLog_To_audit_AuditBackendLog(a.(*AuditBackendLog), b.(*audit.AuditBackendLog), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*audit.AuditBackendLog)(nil), (*AuditBackendLog)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_audit_AuditBackendLog_To_v1alpha1_AuditBackendLog(a.(*audit.AuditBackendLog), b.(*AuditBackendLog), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AuditBackends)(nil), (*audit.AuditBackends)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuditBackends_To_audit_AuditBackends(a.(*AuditBackends), b.(*audit.AuditBackends), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*audit.AuditBackends)(nil), (*AuditBackends)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_audit_AuditBackends_To_v1alpha1_AuditBackends(a.(*audit.AuditBackends), b.(*AuditBackends), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AuditClusterForwarding)(nil), (*audit.AuditClusterForwarding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuditClusterForwarding_To_audit_AuditClusterForwarding(a.(*AuditClusterForwarding), b.(*audit.AuditClusterForwarding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*audit.AuditClusterForwarding)(nil), (*AuditClusterForwarding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_audit_AuditClusterForwarding_To_v1alpha1_AuditClusterForwarding(a.(*audit.AuditClusterForwarding), b.(*AuditClusterForwarding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AuditConfig)(nil), (*audit.AuditConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuditConfig_To_audit_AuditConfig(a.(*AuditConfig), b.(*audit.AuditConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*audit.AuditConfig)(nil), (*AuditConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_audit_AuditConfig_To_v1alpha1_AuditConfig(a.(*audit.AuditConfig), b.(*AuditConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AuditPersistence)(nil), (*audit.AuditPersistence)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuditPersistence_To_audit_AuditPersistence(a.(*AuditPersistence), b.(*audit.AuditPersistence), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*audit.AuditPersistence)(nil), (*AuditPersistence)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_audit_AuditPersistence_To_v1alpha1_AuditPersistence(a.(*audit.AuditPersistence), b.(*AuditPersistence), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AuditBackendLog_To_audit_AuditBackendLog(in *AuditBackendLog, out *audit.AuditBackendLog, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_AuditBackendLog_To_audit_AuditBackendLog is an autogenerated conversion function.
func Convert_v1alpha1_AuditBackendLog_To_audit_AuditBackendLog(in *AuditBackendLog, out *audit.AuditBackendLog, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuditBackendLog_To_audit_AuditBackendLog(in, out, s)
}

func autoConvert_audit_AuditBackendLog_To_v1alpha1_AuditBackendLog(in *audit.AuditBackendLog, out *AuditBackendLog, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_audit_AuditBackendLog_To_v1alpha1_AuditBackendLog is an autogenerated conversion function.
func Convert_audit_AuditBackendLog_To_v1alpha1_AuditBackendLog(in *audit.AuditBackendLog, out *AuditBackendLog, s conversion.Scope) error {
	return autoConvert_audit_AuditBackendLog_To_v1alpha1_AuditBackendLog(in, out, s)
}

func autoConvert_v1alpha1_AuditBackends_To_audit_AuditBackends(in *AuditBackends, out *audit.AuditBackends, s conversion.Scope) error {
	out.Log = (*audit.AuditBackendLog)(unsafe.Pointer(in.Log))
	out.ClusterForwarding = (*audit.AuditClusterForwarding)(unsafe.Pointer(in.ClusterForwarding))
	return nil
}

// Convert_v1alpha1_AuditBackends_To_audit_AuditBackends is an autogenerated conversion function.
func Convert_v1alpha1_AuditBackends_To_audit_AuditBackends(in *AuditBackends, out *audit.AuditBackends, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuditBackends_To_audit_AuditBackends(in, out, s)
}

func autoConvert_audit_AuditBackends_To_v1alpha1_AuditBackends(in *audit.AuditBackends, out *AuditBackends, s conversion.Scope) error {
	out.Log = (*AuditBackendLog)(unsafe.Pointer(in.Log))
	out.ClusterForwarding = (*AuditClusterForwarding)(unsafe.Pointer(in.ClusterForwarding))
	return nil
}

// Convert_audit_AuditBackends_To_v1alpha1_AuditBackends is an autogenerated conversion function.
func Convert_audit_AuditBackends_To_v1alpha1_AuditBackends(in *audit.AuditBackends, out *AuditBackends, s conversion.Scope) error {
	return autoConvert_audit_AuditBackends_To_v1alpha1_AuditBackends(in, out, s)
}

func autoConvert_v1alpha1_AuditClusterForwarding_To_audit_AuditClusterForwarding(in *AuditClusterForwarding, out *audit.AuditClusterForwarding, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_AuditClusterForwarding_To_audit_AuditClusterForwarding is an autogenerated conversion function.
func Convert_v1alpha1_AuditClusterForwarding_To_audit_AuditClusterForwarding(in *AuditClusterForwarding, out *audit.AuditClusterForwarding, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuditClusterForwarding_To_audit_AuditClusterForwarding(in, out, s)
}

func autoConvert_audit_AuditClusterForwarding_To_v1alpha1_AuditClusterForwarding(in *audit.AuditClusterForwarding, out *AuditClusterForwarding, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_audit_AuditClusterForwarding_To_v1alpha1_AuditClusterForwarding is an autogenerated conversion function.
func Convert_audit_AuditClusterForwarding_To_v1alpha1_AuditClusterForwarding(in *audit.AuditClusterForwarding, out *AuditClusterForwarding, s conversion.Scope) error {
	return autoConvert_audit_AuditClusterForwarding_To_v1alpha1_AuditClusterForwarding(in, out, s)
}

func autoConvert_v1alpha1_AuditConfig_To_audit_AuditConfig(in *AuditConfig, out *audit.AuditConfig, s conversion.Scope) error {
	out.Persistence = (*audit.AuditPersistence)(unsafe.Pointer(in.Persistence))
	out.AuditPolicy = (*string)(unsafe.Pointer(in.AuditPolicy))
	out.Backends = (*audit.AuditBackends)(unsafe.Pointer(in.Backends))
	return nil
}

// Convert_v1alpha1_AuditConfig_To_audit_AuditConfig is an autogenerated conversion function.
func Convert_v1alpha1_AuditConfig_To_audit_AuditConfig(in *AuditConfig, out *audit.AuditConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuditConfig_To_audit_AuditConfig(in, out, s)
}

func autoConvert_audit_AuditConfig_To_v1alpha1_AuditConfig(in *audit.AuditConfig, out *AuditConfig, s conversion.Scope) error {
	out.Persistence = (*AuditPersistence)(unsafe.Pointer(in.Persistence))
	out.AuditPolicy = (*string)(unsafe.Pointer(in.AuditPolicy))
	out.Backends = (*AuditBackends)(unsafe.Pointer(in.Backends))
	return nil
}

// Convert_audit_AuditConfig_To_v1alpha1_AuditConfig is an autogenerated conversion function.
func Convert_audit_AuditConfig_To_v1alpha1_AuditConfig(in *audit.AuditConfig, out *AuditConfig, s conversion.Scope) error {
	return autoConvert_audit_AuditConfig_To_v1alpha1_AuditConfig(in, out, s)
}

func autoConvert_v1alpha1_AuditPersistence_To_audit_AuditPersistence(in *AuditPersistence, out *audit.AuditPersistence, s conversion.Scope) error {
	out.Size = (*string)(unsafe.Pointer(in.Size))
	out.StorageClassName = (*string)(unsafe.Pointer(in.StorageClassName))
	return nil
}

// Convert_v1alpha1_AuditPersistence_To_audit_AuditPersistence is an autogenerated conversion function.
func Convert_v1alpha1_AuditPersistence_To_audit_AuditPersistence(in *AuditPersistence, out *audit.AuditPersistence, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuditPersistence_To_audit_AuditPersistence(in, out, s)
}

func autoConvert_audit_AuditPersistence_To_v1alpha1_AuditPersistence(in *audit.AuditPersistence, out *AuditPersistence, s conversion.Scope) error {
	out.Size = (*string)(unsafe.Pointer(in.Size))
	out.StorageClassName = (*string)(unsafe.Pointer(in.StorageClassName))
	return nil
}

// Convert_audit_AuditPersistence_To_v1alpha1_AuditPersistence is an autogenerated conversion function.
func Convert_audit_AuditPersistence_To_v1alpha1_AuditPersistence(in *audit.AuditPersistence, out *AuditPersistence, s conversion.Scope) error {
	return autoConvert_audit_AuditPersistence_To_v1alpha1_AuditPersistence(in, out, s)
}
